version: '3'
services:
  web:
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/aform?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - JWT_SECRET=
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=
      - MYSQL_ROOT_PASSWORD=